baseURL = "http://ceesol.no"
languageCode = "en-us"
title = "ResInsight"
theme = "docdock"

[params]
disableSearch = true
disableNavChevron = true
ordersectionsby = "weight"

[[menu.shortcuts]]
	pre = "<h3>More</h3>"
	name = "<i class='fa fa-github'></i> Github repo"
	identifier = "ds"
	url = "https://github.com/OPM/ResInsight"
	weight = 1
