baseURL = "http://ceesol.no"
languageCode = "en-us"
title = "ResInsight"
theme = "learn"

[params]
disableSearch = false
disableNavChevron = true
disableHomeIcon = true
ordersectionsby = "weight"
themestyle = "flex"

[[menu.shortcuts]]
	name = "Getting Started"
	identifier = "getting-started"
	url = "/getting-started"
	weight = 10

[[menu.shortcuts]]
	name = "Download"
	identifier = "download"
	url = "/project/download"
	weight = 20

[[menu.shortcuts]]
	name = "Project"
	identifier = "project"
	url = "/project"
	weight = 30

